apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: devops-demo-prod
  name: devops-demo-prod
  namespace: devops-demo-prod
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30961
  selector:
    app: kubesphere
    component: devops-demo-prod
    tier: backend
  sessionAffinity: None
  type: NodePort
